In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [6]:
def test(**kwargs):
    for key in kwargs:
        print(key,'=',kwargs[key])
        
test(a='b',c='d')

a = b
c = d


In [4]:
print(y.grad_fn)

In [5]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [6]:
a = torch.randn(2,2)
a = ((a*3) / (a-1))
print(a)

tensor([[ 0.9759,  1.4202],
        [-0.7642,  1.7068]])


In [8]:
torch.tensor([[1,2],[3,4]]) @ torch.tensor([[1,1],[1,1]])

tensor([[3, 3],
        [7, 7]])

In [7]:
print(a.requires_grad)

False


In [8]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [9]:
b = ( a* a).sum()
print(b, b.grad_fn)

tensor(6.4667, grad_fn=<SumBackward0>) <SumBackward0 object at 0x000002A4B9CCD978>


In [10]:
out.backward()

In [11]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [12]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y *2
    
print(y)

tensor([-565.1384,  508.8299,  658.4619], grad_fn=<MulBackward0>)


In [13]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [14]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
